
create database SonoraInc
go


use SonoraInc
go
-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-04-28 14:48:31 ECT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Album 
    (
     idAlbum INTEGER NOT NULL , 
     tituloAlbum VARCHAR (50) NOT NULL , 
     fechaLanzamientoAlbum DATE NOT NULL 
    )
GO

ALTER TABLE Album ADD CONSTRAINT Album_PK PRIMARY KEY CLUSTERED (idAlbum)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Artista 
    (
     idArtista INTEGER NOT NULL , 
     nombreArtista VARCHAR (50) NOT NULL , 
     paisOrigenArtista VARCHAR (50) NOT NULL , 
     descripcionArtista VARCHAR (50) , 
     Productora_idProductora INTEGER NOT NULL 
    )
GO

ALTER TABLE Artista ADD CONSTRAINT Artista_PK PRIMARY KEY CLUSTERED (idArtista)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ArtistaCancion 
    (
     Artista_idArtista INTEGER NOT NULL , 
     Cancion_idCancion INTEGER NOT NULL 
    )
GO

ALTER TABLE ArtistaCancion ADD CONSTRAINT ArtistaCancion_PK PRIMARY KEY CLUSTERED (Artista_idArtista, Cancion_idCancion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Cancion 
    (
     idCancion INTEGER NOT NULL , 
     tituloCancion VARCHAR (50) NOT NULL , 
     duracionCancion FLOAT NOT NULL , 
     idiomaCancion VARCHAR (50) , 
     Genero_idGenero INTEGER NOT NULL , 
     Album_idAlbum INTEGER 
    )
GO 


ALTER TABLE Cancion 
    ADD CONSTRAINT CONSTRAIN_duracionCancion 
    CHECK ( duracionCancion BETWEEN 0.10 AND 10000000 ) 
GO

ALTER TABLE Cancion ADD CONSTRAINT Cancion_PK PRIMARY KEY CLUSTERED (idCancion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CancionPlaylist 
    (
     Cancion_idCancion INTEGER NOT NULL , 
     Playlist_idPlaylist INTEGER NOT NULL 
    )
GO

ALTER TABLE CancionPlaylist ADD CONSTRAINT CancionPlaylist_PK PRIMARY KEY CLUSTERED (Cancion_idCancion, Playlist_idPlaylist)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Genero 
    (
     idGenero INTEGER NOT NULL , 
     nombreGenero VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Genero ADD CONSTRAINT Genero_PK PRIMARY KEY CLUSTERED (idGenero)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Genero ADD CONSTRAINT Genero_nombreGenero_UN UNIQUE NONCLUSTERED (nombreGenero)
GO

CREATE TABLE Pago 
    (
     idPago INTEGER NOT NULL , 
     fechaPago DATE NOT NULL , 
     montoPago DECIMAL (10,2) NOT NULL , 
     Suscripcion_idSuscripcion INTEGER NOT NULL 
    )
GO

ALTER TABLE Pago ADD CONSTRAINT Pago_PK PRIMARY KEY CLUSTERED (idPago)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Playlist 
    (
     idPlaylist INTEGER NOT NULL , 
     nombrePlaylist VARCHAR (50) NOT NULL , 
     fechaCreacionPlaylist DATE NOT NULL , 
     privacidadPlaylist VARCHAR (50) NOT NULL DEFAULT 'Privada' , 
     descripcionPlaylist VARCHAR (50) , 
     Usuario_idUsuario INTEGER NOT NULL 
    )
GO 


ALTER TABLE Playlist 
    ADD CONSTRAINT CHK_privacidadPlaylist 
    CHECK ( privacidadPlaylist IN ('Privada', 'Publica') ) 
GO

ALTER TABLE Playlist ADD CONSTRAINT Playlist_PK PRIMARY KEY CLUSTERED (idPlaylist)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Productora 
    (
     idProductora INTEGER NOT NULL , 
     nombreProductora VARCHAR (50) NOT NULL , 
     paisProductora VARCHAR (50) NOT NULL , 
     correoProductora VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Productora ADD CONSTRAINT Productora_PK PRIMARY KEY CLUSTERED (idProductora)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Productora ADD CONSTRAINT Productora_correoProductora_UN UNIQUE NONCLUSTERED (correoProductora)
GO

CREATE TABLE Regalia 
    (
     idRegalia INTEGER NOT NULL , 
     cantidadReproduccionesRegalia INTEGER NOT NULL , 
     montoGeneradoRegalia DECIMAL (10,2) NOT NULL , 
     fechaCalculoRegalia DATE NOT NULL , 
     Cancion_idCancion INTEGER NOT NULL 
    )
GO

ALTER TABLE Regalia ADD CONSTRAINT Regalia_PK PRIMARY KEY CLUSTERED (idRegalia)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Reproduccion 
    (
     idReproduccion INTEGER NOT NULL , 
     fechaReproduccion DATE NOT NULL , 
     duracionReproduccion FLOAT NOT NULL , 
     Usuario_idUsuario INTEGER NOT NULL , 
     Cancion_idCancion INTEGER NOT NULL 
    )
GO

ALTER TABLE Reproduccion ADD CONSTRAINT Reproduccion_PK PRIMARY KEY CLUSTERED (idReproduccion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Suscripcion 
    (
     idSuscripcion INTEGER NOT NULL , 
     tipoPlanSuscripcion VARCHAR (50) NOT NULL DEFAULT 'Gratis' , 
     fechaInicioSuscripcion DATE NOT NULL , 
     fechaFinSuscripcion DATE , 
     estadoSuscripcion VARCHAR (50) , 
     Usuario_idUsuario INTEGER NOT NULL 
    )
GO 


ALTER TABLE Suscripcion 
    ADD CONSTRAINT CHK_tipoPlanSuscripcion 
    CHECK ( tipoPlanSuscripcion IN ('Gratis', 'Premium') ) 
GO


ALTER TABLE Suscripcion 
    ADD CONSTRAINT CHK_estadoSuscripcion 
    CHECK ( estadoSuscripcion IN ('Activa', 'Cancelada', 'Vencida') ) 
GO

ALTER TABLE Suscripcion ADD CONSTRAINT Suscripcion_PK PRIMARY KEY CLUSTERED (idSuscripcion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Usuario 
    (
     idUsuario INTEGER NOT NULL , 
     nombreUsuario VARCHAR (50) NOT NULL , 
     apellidoUsuario VARCHAR (50) NOT NULL , 
     segundoNombreUsuario VARCHAR (50) , 
     segundoApellidoUsuario VARCHAR (50) , 
     correoUsuario VARCHAR (50) NOT NULL , 
     fechaRegistroUsuario DATE NOT NULL 
    )
GO

ALTER TABLE Usuario ADD CONSTRAINT Usuario_PK PRIMARY KEY CLUSTERED (idUsuario)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Usuario ADD CONSTRAINT Usuario_correoUsuario_UN UNIQUE NONCLUSTERED (correoUsuario)
GO

CREATE TABLE UsuarioArtista 
    (
     Usuario_idUsuario INTEGER NOT NULL , 
     Artista_idArtista INTEGER NOT NULL 
    )
GO

ALTER TABLE UsuarioArtista ADD CONSTRAINT UsuarioArtista_PK PRIMARY KEY CLUSTERED (Usuario_idUsuario, Artista_idArtista)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE UsuarioCancion 
    (
     Usuario_idUsuario INTEGER NOT NULL , 
     Cancion_idCancion INTEGER NOT NULL 
    )
GO

ALTER TABLE UsuarioCancion ADD CONSTRAINT UsuarioCancion_PK PRIMARY KEY CLUSTERED (Usuario_idUsuario, Cancion_idCancion)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Artista 
    ADD CONSTRAINT Artista_Productora_FK FOREIGN KEY 
    ( 
     Productora_idProductora
    ) 
    REFERENCES Productora 
    ( 
     idProductora 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ArtistaCancion 
    ADD CONSTRAINT ArtistaCancion_Artista_FK FOREIGN KEY 
    ( 
     Artista_idArtista
    ) 
    REFERENCES Artista 
    ( 
     idArtista 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ArtistaCancion 
    ADD CONSTRAINT ArtistaCancion_Cancion_FK FOREIGN KEY 
    ( 
     Cancion_idCancion
    ) 
    REFERENCES Cancion 
    ( 
     idCancion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Cancion 
    ADD CONSTRAINT Cancion_Album_FK FOREIGN KEY 
    ( 
     Album_idAlbum
    ) 
    REFERENCES Album 
    ( 
     idAlbum 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Cancion 
    ADD CONSTRAINT Cancion_Genero_FK FOREIGN KEY 
    ( 
     Genero_idGenero
    ) 
    REFERENCES Genero 
    ( 
     idGenero 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CancionPlaylist 
    ADD CONSTRAINT CancionPlaylist_Cancion_FK FOREIGN KEY 
    ( 
     Cancion_idCancion
    ) 
    REFERENCES Cancion 
    ( 
     idCancion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CancionPlaylist 
    ADD CONSTRAINT CancionPlaylist_Playlist_FK FOREIGN KEY 
    ( 
     Playlist_idPlaylist
    ) 
    REFERENCES Playlist 
    ( 
     idPlaylist 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Pago 
    ADD CONSTRAINT Pago_Suscripcion_FK FOREIGN KEY 
    ( 
     Suscripcion_idSuscripcion
    ) 
    REFERENCES Suscripcion 
    ( 
     idSuscripcion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Playlist 
    ADD CONSTRAINT Playlist_Usuario_FK FOREIGN KEY 
    ( 
     Usuario_idUsuario
    ) 
    REFERENCES Usuario 
    ( 
     idUsuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Regalia 
    ADD CONSTRAINT Regalia_Cancion_FK FOREIGN KEY 
    ( 
     Cancion_idCancion
    ) 
    REFERENCES Cancion 
    ( 
     idCancion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Reproduccion 
    ADD CONSTRAINT Reproduccion_Cancion_FK FOREIGN KEY 
    ( 
     Cancion_idCancion
    ) 
    REFERENCES Cancion 
    ( 
     idCancion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Reproduccion 
    ADD CONSTRAINT Reproduccion_Usuario_FK FOREIGN KEY 
    ( 
     Usuario_idUsuario
    ) 
    REFERENCES Usuario 
    ( 
     idUsuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Suscripcion 
    ADD CONSTRAINT Suscripcion_Usuario_FK FOREIGN KEY 
    ( 
     Usuario_idUsuario
    ) 
    REFERENCES Usuario 
    ( 
     idUsuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UsuarioArtista 
    ADD CONSTRAINT UsuarioArtista_Artista_FK FOREIGN KEY 
    ( 
     Artista_idArtista
    ) 
    REFERENCES Artista 
    ( 
     idArtista 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UsuarioArtista 
    ADD CONSTRAINT UsuarioArtista_Usuario_FK FOREIGN KEY 
    ( 
     Usuario_idUsuario
    ) 
    REFERENCES Usuario 
    ( 
     idUsuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UsuarioCancion 
    ADD CONSTRAINT UsuarioCancion_Cancion_FK FOREIGN KEY 
    ( 
     Cancion_idCancion
    ) 
    REFERENCES Cancion 
    ( 
     idCancion 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UsuarioCancion 
    ADD CONSTRAINT UsuarioCancion_Usuario_FK FOREIGN KEY 
    ( 
     Usuario_idUsuario
    ) 
    REFERENCES Usuario 
    ( 
     idUsuario 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
